project:
  description: Amazon::S3::Lite
  author:
    name: Rob Lauer
    mailto: rlauer@treasurersbriefcase.com
pm-module: Amazon::S3::Lite
min-perl-version: 5.010
dependencies:
  requires: requires
  test-requires: test-requires
path:
  pm-module: lib
  exe-files: bin
  tests: t
extra-files:
  - ChangeLog
  - share:
      - README.md
resources:
  homepage: http://github.com/rlauer6/Amazon-S3-Lite.git
  bugtracker:
    web: http://github.com/rlauer6/Amazon-S3-Lite/issues
    mailto: rlauer@treasurersbriefcase.com
  repository:
    url: git://github.com/rlauer6/Amazon-S3-Lite.git
    web: http://github.com/rlauer6/Amazon-S3-Lite.git
    type: 'git'
