requires "IO::Socket::SSL", "0";
requires "Net::SSLeay", "0";
requires "Amazon::Signature4::Lite", "1.0.0";
requires "HTTP::Tiny", "0";
requires "HTTP::Tiny", "0.088";
requires "IO::Scalar", "0";
requires "JSON::PP", "4.16";
requires "URI::Escape", "5.34";
requires "XML::Twig", "0";
